export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL";

export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_REQUEST = "UNFOLLOW_USER_REQUEST";
export const UNFOLLOW_USER_FAIL = "UNFOLLOW_USER_FAIL";
