export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
