export const FRIEND_REQUEST_SUCCESS = "FRIEND_REQUEST_SUCCESS";
export const FRIEND_REQUEST_REQUEST = "FRIEND_REQUEST_REQUEST";
export const FRIEND_REQUEST_FAIL = "FRIEND_REQUEST_FAIL";

export const INCOMING_REQUEST_SUCCESS = "INCOMING_REQUEST_SUCCESS";
export const INCOMING_REQUEST_REQUEST = "INCOMING_REQUEST_REQUEST";
export const INCOMING_REQUEST_FAIL = "INCOMING_REQUEST_FAIL";

export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const ACCEPT_REQUEST_REQUEST = "ACCEPT_REQUEST_REQUEST";
export const ACCEPT_REQUEST_FAIL = "ACCEPT_REQUEST_FAIL";

export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS";
export const GET_FOLLOWERS_REQUEST = "GET_FOLLOWERS_REQUEST";
export const GET_FOLLOWERS_FAIL = "GET_FOLLOWERS_FAIL";

export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_FAIL = "GET_FRIENDS_FAIL";

export const CHECK_FRIENDS_SUCCESS = "CHECK_FRIENDS_SUCCESS";
export const CHECK_FRIENDS_REQUEST = "CHECK_FRIENDS_REQUEST";
export const CHECK_FRIENDS_FAIL = "CHECK_FRIENDS_FAIL";
